spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow: "*"
      web-stat-filter:
        enabled: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    dynamic:
      primary: private
      strict: false
      # 数据源懒加载
      lazy: true
      druid:
        # 池初始化大小
        initial-size: 8
        # 最少存活连接数
        min-idle: 2
        # 最多活跃连接数
        maxActive: 16
        # 获取连接等待超时时间
        maxWait: 60000
        # 空闲连接检测间隔
        timeBetweenEvictionRunsMillis: 60000
        # 最小生存时间
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # stat 监控统计
        # wall 防御SQL注入
        filters: stat,wall,log4j
        # 开启mergeSql功能
        # slowSQL
        useGlobalDataSourceStat: true
      datasource:
        private:
          driver-class-name: com.mysql.cj.jdbc.Driver
#          本机
#          url: jdbc:mysql://localhost:3306/fsmm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&
#          username: root
#          password: 123456
#          服务器
          url: jdbc:mysql://122.205.95.110:3366/swine?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true&useSSL=false
#          url: jdbc:mysql://122.205.95.110:3366/swine
          username: root
          password: root



  application:
    name: swine-search-project
  servlet:
    multipart:
      max-file-size: 10000000000  #最大上传单个文件大小：默认1M
      max-request-size: 1024000000 #最大总上传的数据大小:默认10M(对同时上传多个文件大小的限制）

      # 配置邮件服务器的地址
  mail:
    host: smtp.qq.com
    port: 465   # 配置邮件服务器的端口（465或587）
    username: 794301701@qq.com   # 配置用户的账号
    password: jdqhbrgyvyukbecj   # 配置用户的密码（即上面我们申请到的授权码）
    default-encoding: UTF-8  # 配置默认编码
    properties:
      mail:
#        debug:true  #启动debug调试
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置

server:
  port: 8080

springdoc:
  packages-to-scan: com.example.swinedatebaseproject.controller
  swagger-ui:
    path: /api-docs
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true


